server:
  port: 8888

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    name: test
    url: jdbc:mysql://39.108.128.195:3306/arvinzhang
    username: root
    password: arvinzhang
    # Druid数据库连接
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

## mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.xifeng.kuandai.dto
#pagehelper分页
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql